version: '3'
services:
    redis: 
        image: 'redis'
        ports: 
            - 6379:6379
    mongo:
        image: mongo
        ports: 
            - 27017:27017
        volumes: 
            - /home/pvposso/mongodata/mongoDB:/data/db
    transations-api:
        ports:
            - 5000:80
        build:
            context: .
        environment:
            - REDIS_PORT=6379
            - REDIS_HOST=redis
            - MONGODB_URI=mongodb://mongo:27017/transactions
        depends_on:
            - redis
            - mongo